# Lab #1

підключимаємо різні модулі 

In [23]:
import csv
import numpy as np
import random

зчитаємо дані з файлу "prob_XX.csv"

In [2]:
prob = []
with open('../vars/prob_16.csv', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in reader:    
        prob.append(row[0])
        
print(prob)

['0.24,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04', '0.22,0.22,0.22,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02']


розділимо зчитані дані на ймовірнісні розподіли ВТ і ключів

In [3]:
PT_dist = prob[0].split(',')
for i in range(len(PT_dist)):
    PT_dist[i] = float(PT_dist[i])
    
print('Plaintext distribution: ', PT_dist)

keys_dist = prob[1].split(',')
for i in range(len(keys_dist)):
    keys_dist[i] = float(keys_dist[i])
    
print('\nKeys distribution: ', keys_dist)

Plaintext distribution:  [0.24, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04]

Keys distribution:  [0.22, 0.22, 0.22, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]


зчитаємо дані з файлу "table_XX.csv", та перетворимо їх в "нормальний" вигляд

In [4]:
table = []
with open('../vars/table_16.csv', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in reader:    
        table.append(row[0])
for i in range(len(table)):
    table[i] = table[i].split(',')
    for j in range(len(table[i])):
        table[i][j] = int(table[i][j])
        
print(np.matrix(table))

[[ 6  7  9 10  2 17 13  8 11  0 16 12 15 18 19  3  5  4 14  1]
 [ 5 14  7  9 16  3  8  6  4  2 12 15 13 17  0 10 18  1 19 11]
 [ 5  3 18  4  0  2  1 16  9 14 17  8 19 12  7 10  6 13 15 11]
 [14  0 17  8 16  6 13  9  1  4 15  7 18 19 10 12  5  3 11  2]
 [ 2  7 12  8  1 17 11 19  6 14  3  5 10  0 16  9 13 18  4 15]
 [ 2  0 12  9 19  7 11  6 14 16  5 13 10  4 15 17  1 18  3  8]
 [ 5  6 15  8  0  3 18 10 12 16  4 13 19  1 11  9 14  2  7 17]
 [12  8  7  1  9 17 13 19  4  5  6  2 10 18 16  3  0 11 15 14]
 [17 13 18  7  6 16 19 14  2  8  4  3  5 12 15  1  9 10  0 11]
 [12 17  6 13 11 15 18 10  3  0  5 14  1  2  8 16  4 19  9  7]
 [16  5 18  1 15 19 14 11  3 13  4  2  0  8 12  6  7  9 17 10]
 [ 7  6  0 17 12 14 11  1 18  2  3 19  8  9 15 10 13 16  5  4]
 [ 6  5 16 19 18  9  3  1 15  0 14 17  8 11 13 10  4  2  7 12]
 [12 17 15  7  1 19 11 13  5 16  8 14  4  0 18  3  2 10  9  6]
 [ 9 18 12 14  0 17  4  8 16  3 13  7  1 11 10  2 19 15  6  5]
 [ 5 11  4 14  0 16 15  8  2 13  3  6 18  1 12  7 19 10

знайдемо розподіл шифротекстів таким чином:
$P(C) = \sum\limits_{\forall (M,k): E_k(M)=C}P(M,k)$, де $P(M,k) = P(M) \cdot P(k)$.

In [14]:
CT_dist = []
for i in range(20):
    CT_dist.append(0)
    for key_index in range(20):
        for PT_index in range(20):
            if (table[key_index][PT_index] == i):
                CT_dist[i] += PT_dist[PT_index] * keys_dist[key_index]

#далі ми округлюємо, через особливості чисел з плаваючою точкою        
for i in range(20):
    CT_dist[i] = round(CT_dist[i], 3)

print('Ciphertext distribution: ', CT_dist)

Ciphertext distribution:  [0.04, 0.044, 0.048, 0.04, 0.04, 0.136, 0.088, 0.048, 0.04, 0.048, 0.04, 0.04, 0.052, 0.04, 0.048, 0.04, 0.044, 0.044, 0.04, 0.04]


знайдемо розподіл $P(M,C)=\sum\limits_{\forall k: E_k(M)=C}P(M,k)$

In [19]:
comp_dist = [[0 for i in range(20)] for i in range(20)]
for key_index in range(20):
    for CT_index in range(20):
        for PT_index in range(20):
            if (table[key_index][PT_index] == CT_index):
                comp_dist[PT_index][CT_index] += PT_dist[PT_index] * keys_dist[key_index]

print('Ciphertext and plaintext compatible distribution:\n\n', np.matrix(comp_dist))

Ciphertext and plaintext compatible distribution:

 [[0.     0.0048 0.0096 0.     0.     0.1152 0.0576 0.0096 0.     0.0096
  0.     0.     0.0144 0.     0.0096 0.     0.0048 0.0048 0.     0.    ]
 [0.0016 0.     0.     0.0088 0.     0.0016 0.0016 0.0096 0.0008 0.
  0.0008 0.0008 0.     0.0016 0.0088 0.     0.     0.0024 0.0008 0.0008]
 [0.0008 0.     0.     0.     0.0016 0.     0.0008 0.0096 0.     0.0088
  0.     0.     0.0024 0.     0.     0.0024 0.0016 0.0008 0.0104 0.0008]
 [0.     0.0016 0.     0.     0.0088 0.     0.     0.0016 0.0024 0.0096
  0.0088 0.     0.0008 0.0016 0.0016 0.     0.0008 0.0008 0.0008 0.0008]
 [0.0112 0.0016 0.0096 0.     0.     0.0008 0.0008 0.     0.     0.0008
  0.0008 0.0008 0.0008 0.     0.0008 0.0008 0.0096 0.     0.0008 0.0008]
 [0.     0.     0.0096 0.0112 0.     0.     0.0008 0.0016 0.     0.0008
  0.     0.     0.     0.     0.0008 0.0008 0.0016 0.0112 0.     0.0016]
 [0.     0.0088 0.     0.0008 0.0008 0.     0.     0.     0.0096 0.
  0.0008 0.003

обрахуємо розподіл умовних імовірностей $P(C|M)$

In [22]:
cond_dist = [[0 for i in range(20)] for i in range(20)]
for PT_index in range(20):
    for CT_index in range(20):
        cond_dist[PT_index][CT_index] = comp_dist[PT_index][CT_index] / CT_dist[CT_index]
        
for i in range(20):
    for j in range(20):
        cond_dist[i][j] = round(cond_dist[i][j], 3)
print('Conditional distribution P(M|C): \n\n', np.matrix(cond_dist))

Conditional distribution P(M|C): 

 [[0.    0.109 0.2   0.    0.    0.847 0.655 0.2   0.    0.2   0.    0.
  0.277 0.    0.2   0.    0.109 0.109 0.    0.   ]
 [0.04  0.    0.    0.22  0.    0.012 0.018 0.2   0.02  0.    0.02  0.02
  0.    0.04  0.183 0.    0.    0.055 0.02  0.02 ]
 [0.02  0.    0.    0.    0.04  0.    0.009 0.2   0.    0.183 0.    0.
  0.046 0.    0.    0.06  0.036 0.018 0.26  0.02 ]
 [0.    0.036 0.    0.    0.22  0.    0.    0.033 0.06  0.2   0.22  0.
  0.015 0.04  0.033 0.    0.018 0.018 0.02  0.02 ]
 [0.28  0.036 0.2   0.    0.    0.006 0.009 0.    0.    0.017 0.02  0.02
  0.015 0.    0.017 0.02  0.218 0.    0.02  0.02 ]
 [0.    0.    0.2   0.28  0.    0.    0.009 0.033 0.    0.017 0.    0.
  0.    0.    0.017 0.02  0.036 0.255 0.    0.04 ]
 [0.    0.2   0.    0.02  0.02  0.    0.    0.    0.24  0.    0.02  0.08
  0.015 0.26  0.017 0.02  0.018 0.    0.04  0.02 ]
 [0.    0.055 0.    0.    0.    0.    0.118 0.    0.26  0.017 0.04  0.02
  0.    0.02  0.033 0.    0.2  

реалізуємо детерміністичну вирішуючу функцію

In [28]:
def det_func (CT):
    result_arr = []
    for PT_index in range(20):
        for key_index in range(20):
            if (table[PT_index][key_index] == CT):
                result_arr.append(PT_index)
    return random.choice(result_arr)