# Lab #1

підключимаємо різні модулі 

In [32]:
import csv
import numpy as np

зчитаємо дані з файлу "prob_XX.csv"

In [33]:
prob = []
with open('../vars/prob_16.csv', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in reader:    
        prob.append(row[0])
        
print(prob)

['0.24,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04', '0.22,0.22,0.22,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02']


розділимо зчитані дані на ймовірнісні розподіли ВТ і ключів

In [34]:
PT_dist = prob[0].split(',')
for i in range(len(PT_dist)):
    PT_dist[i] = float(PT_dist[i])
    
print('Plaintext distribution: ', PT_dist)

keys_dist = prob[1].split(',')
for i in range(len(keys_dist)):
    keys_dist[i] = float(keys_dist[i])
    
print('\nKeys distribution: ', keys_dist)

Plaintext distribution:  [0.24, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04]

Keys distribution:  [0.22, 0.22, 0.22, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]


зчитаємо дані з файлу "table_XX.csv", та перетворимо їх в "нормальний" вигляд

In [35]:
table = []
with open('../vars/table_16.csv', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in reader:    
        table.append(row[0])
for i in range(len(table)):
    table[i] = table[i].split(',')
    for j in range(len(table[i])):
        table[i][j] = int(table[i][j])
        
print(np.matrix(table))

[[ 6  7  9 10  2 17 13  8 11  0 16 12 15 18 19  3  5  4 14  1]
 [ 5 14  7  9 16  3  8  6  4  2 12 15 13 17  0 10 18  1 19 11]
 [ 5  3 18  4  0  2  1 16  9 14 17  8 19 12  7 10  6 13 15 11]
 [14  0 17  8 16  6 13  9  1  4 15  7 18 19 10 12  5  3 11  2]
 [ 2  7 12  8  1 17 11 19  6 14  3  5 10  0 16  9 13 18  4 15]
 [ 2  0 12  9 19  7 11  6 14 16  5 13 10  4 15 17  1 18  3  8]
 [ 5  6 15  8  0  3 18 10 12 16  4 13 19  1 11  9 14  2  7 17]
 [12  8  7  1  9 17 13 19  4  5  6  2 10 18 16  3  0 11 15 14]
 [17 13 18  7  6 16 19 14  2  8  4  3  5 12 15  1  9 10  0 11]
 [12 17  6 13 11 15 18 10  3  0  5 14  1  2  8 16  4 19  9  7]
 [16  5 18  1 15 19 14 11  3 13  4  2  0  8 12  6  7  9 17 10]
 [ 7  6  0 17 12 14 11  1 18  2  3 19  8  9 15 10 13 16  5  4]
 [ 6  5 16 19 18  9  3  1 15  0 14 17  8 11 13 10  4  2  7 12]
 [12 17 15  7  1 19 11 13  5 16  8 14  4  0 18  3  2 10  9  6]
 [ 9 18 12 14  0 17  4  8 16  3 13  7  1 11 10  2 19 15  6  5]
 [ 5 11  4 14  0 16 15  8  2 13  3  6 18  1 12  7 19 10

знайдемо розподіл шифротекстів таким чином:
$P(C) = \sum\limits_{\forall (M,k): E_k(M)=C}P(M,k)$, де $P(M,k) = P(M) \cdot P(k)$.

In [36]:
CT_dist = []
for i in range(20):
    CT_dist.append(0)
    for PT_index in range(20):
        for key_index in range(20):
            if (table[PT_index][key_index] == i):
                CT_dist[i] += PT_dist[PT_index] * keys_dist[key_index]

#далі ми округлюємо, через особливості чисел з плаваючою точкою        
for i in range(20):
    CT_dist[i] = round(CT_dist[i], 3)

print('Ciphertext distribution: ', CT_dist)

Ciphertext distribution:  [0.044, 0.028, 0.036, 0.028, 0.036, 0.068, 0.1, 0.108, 0.028, 0.084, 0.028, 0.028, 0.068, 0.036, 0.044, 0.044, 0.044, 0.06, 0.052, 0.036]


знайдемо розподіл $P(M,C)$

In [40]:
table_1 = [[0 for i in range(20)] for i in range(20)]
for PT_index in range(20):
    for CT_index in range(20):
        for key_index in range(20):
            if (table[PT_index][key_index] == CT_index):
                table_1[PT_index][CT_index] += PT_dist[PT_index] * keys_dist[key_index]

print(np.matrix(table_1))

[[0.0048 0.0048 0.0048 0.0048 0.0048 0.0048 0.0528 0.0528 0.0048 0.0528
  0.0048 0.0048 0.0048 0.0048 0.0048 0.0048 0.0048 0.0048 0.0048 0.0048]
 [0.0008 0.0008 0.0008 0.0008 0.0008 0.0088 0.0008 0.0088 0.0008 0.0008
  0.0008 0.0008 0.0008 0.0008 0.0088 0.0008 0.0008 0.0008 0.0008 0.0008]
 [0.0008 0.0008 0.0008 0.0088 0.0008 0.0088 0.0008 0.0008 0.0008 0.0008
  0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0088 0.0008]
 [0.0088 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008
  0.0008 0.0008 0.0008 0.0008 0.0088 0.0008 0.0008 0.0088 0.0008 0.0008]
 [0.0008 0.0008 0.0088 0.0008 0.0008 0.0008 0.0008 0.0088 0.0008 0.0008
  0.0008 0.0008 0.0088 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008]
 [0.0088 0.0008 0.0088 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008
  0.0008 0.0008 0.0088 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008 0.0008]
 [0.0008 0.0008 0.0008 0.0008 0.0008 0.0088 0.0088 0.0008 0.0008 0.0008
  0.0008 0.0008 0.0008 0.0008 0.0008 0.0088 0.0008 0.0008 